name: always
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: |
          echo "job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2
        run: |
          exit 1
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()
    steps:
      - name: job3
        run: |
          echo "job3"
