name: container test
on: push

jobs:
  service-container-test:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: echo "job1"
      - name: job2
        run: exit 1
      - name: job3
        if: ${{ always() }}
        run: echo "job3"
