name: always
on: push

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: lock
        run: |
          echo "lock"
  test:
    runs-on: ubuntu-latest
    needs: lock
    steps:
      - name: test
        run: |
          exit 0
  unlock:
    runs-on: ubuntu-latest
    needs: [lock, test]
    if: always()
    steps:
      - name: unlock
        run: |
          echo "unlock"
