name: check branch name
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: actions/checkout@v4
      - name: echo branch name
        run: echo ${{ github.head_ref }}
      # ブランチ名が Fではじまらない または -with-e2e で終わらない場合はエラー echo 'branch name is invalid'
      # startswith と endswith と if で実装してみる
      - name: Check branch name amd
        if: ${{ !startsWith(github.head_ref, 'F') && !endsWith(github.head_ref, '-with-e2e') }}
        run: echo 'branch name is valid'
      - name: Check branch name or
        if: ${{ !startsWith(github.head_ref, 'F') || !endsWith(github.head_ref, '-with-e2e') }}
        run: echo 'branch name is valid'
