name: container
on: push

jobs:
  container-test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - name: go version
      run: go version

  service-container-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env: 
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
        ports: 
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: ps
        run: ps -aux
