name: trigger directory changes

on:
  - push

jobs:
  list-changes-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files changed
        run: |

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      contains-hoge: ${{ steps.check-diff.outputs.contains-hoge }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check branch
        run: |
          git branch -a
      - name: Check if diff contains hoge
        id: check-diff
        run: |
          git diff --name-only origin/main...HEAD
