name: trigger directory changes

on:
  - push

jobs:
  list-changes-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files changed
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
