name: trigger directory changes

on:
  - push

jobs:
  check_changes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [file1, file2, file3, file4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check branch
        run: |
          git branch -a
      - name: Check if diff contains hoge
        id: check-diff
        run: |
          changed_file=$(git diff --name-only origin/main..HEAD | grep ${{ matrix.file }} || true)
          if [ -n "$changed_file" ]; then
          directory=$(dirname "$changed_file")
          echo "Moving to directory $directory"
          cd "$directory"
          pwd
          else
          echo "${{ matrix.file}} was not changed. Skipping this step."
          fi
