name: trigger directory changes

on:
  - push

jobs:
  list-changes-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files changed
        run: |
          echo ${{ github.sha }}
          echo ${{ github.event.before }}
          echo ${{ github.event.after }}
