name: disk-check
on: workflow_dispatch
  

jobs:
  df:
    runs-on: ubuntu-latest
    steps:
      - run: df -h
  create-file:
    runs-on: ubuntu-latest
    steps:
      - run: fallocate -l 20G output_file
      - run: df -h

