name: Dynamic matrix strategy
on:
  workflow_dispatch:
    inputs:
      development:
        required: true
        type: boolean
        default: false
      staging:
        required: true
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.check-targets.outputs.targets }}
    steps:
      - id: check-targets
        run: |
            targets=$(jq -cn \
            --argjson development ${{ fromJson(github.event.inputs.development) }} \
            --argjson staging ${{ fromJson(github.event.inputs.staging) }} \
            '{
                environments: [
                (if $development then "development" else empty end),
                (if $staging then "staging" else empty end)
                ]
            }')
            echo "targets=${targets}" >> $GITHUB_OUTPUT

  execute:
    needs: check
    runs-on: ubuntu-latest
    strategy:
        matrix:
          environment: ${{ fromJSON(needs.check.outputs.targets).environments }}
    steps:
        - run: echo " Do something in ${{ matrix.environment }}"
