name: Dynamic matrix strategy
on:
  workflow_dispatch:
    inputs:
      development:
        required: true
        type: boolean
        default: false
      staging:
        required: true
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.check-targets.outputs.targets }}
    steps: # inputs のうち、 true のものを 配列に追加。{"environtmnes": ["development", "staging"]} といった形式で出力
      - id: check-targets
        run: |
            environments=()
            if [ ${{ fromJson(github.event.inputs.development) }} ]; then
                targets+=('development')
            fi
            if [ ${{ fromJson(github.event.inputs.staging) }} ]; then
                targets+=('staging')
            fi
            echo $environments
            echo "targets={\"environments\": [\"${environments[*]}\"]}" >> $GITHUB_OUTPUT

  deploy:
    needs: check
    runs-on: ubuntu-latest
    # strategy:
    #     matrix:
    #       environment: ${{ fromJSON(needs.check.outputs.targets).environments }}
    steps:
        - run: echo "Deploy for ${{ needs.check.outputs.targets }}"
