name: Dynamic matrix strategy
on:
  workflow_dispatch:
    inputs:
      development:
        required: true
        type: boolean
        default: false
      staging:
        required: true
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.check-targets.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo inputs
        run: |
            echo "${{ toJson(inputs) }}"
            echo "${{ toJson(github.event.inputs) }}"
      - name: Validate inputs
        if: ${{ !inputs.development && !inputs.staging }}
        run: echo "At least one of environments must be true." && exit 1
      - id: check-targets
        run: |
            targets="$(jq -cn \
            --argjson development ${{ inputs.development }} \
            --argjson staging ${{ inputs.staging }} \
            '[
                (if $development then "development" else empty end),
                (if $staging then "staging" else empty end)
            ]')"
            echo "targets=${targets}" >> "$GITHUB_OUTPUT"

  execute:
    needs: check
    runs-on: ubuntu-latest
    strategy:
        matrix:
          environment: ${{ fromJSON(needs.check.outputs.targets) }}
    steps:
        - run: echo "Do something in ${{ matrix.environment }}"
