name: set debug

on: push

jobs:
  echo-env:
      runs-on: ubuntu-latest
      steps:
        - name: set debug
          run: |
            echo "::debug::Debug Message!!"
            env
  set-output:
      runs-on: ubuntu-latest
      steps:
        - id: set-output-step-test
          name: set-output
          run: |
            echo "::set-output name=output::hogehoge"
        - run:
            echo "${{ steps.set-output-step-test.outputs.output }}"
