name: Matrix Jobs

on:
  workflow_dispatch:
  push:

jobs:
  test:
    strategy:
      matrix:
        value: [ubuntu-latest, large-runner-for-backend-ci]
    runs-on: ubuntu-latest
    steps:
        - run: echo "Hello, ${{ matrix.value }}"
        - run: exit 1

  notify-failure:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ failure() }}
    steps:
      - run: echo "Test failed"

  notify-result-failure:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ always() && needs.test.result == 'failure' }}
    steps:
      - run: echo "Test failed"
