name: test my action
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
        default: "World"
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check node version
        run: node --version
      - name: setup-node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "20.10.0"
      - name: check node version
        run: node --version
      - uses: fchimpan/github-actions@v1.1
        with:
          who-to-greet: ${{ github.event.inputs.name }}
