name: Update Schedule Difference JSON 30 min

on:
  schedule:
    - cron: "0 * * * *" # 毎時0分に実行
  workflow_dispatch:

jobs:
  update-json:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Calculate time difference and update JSON
        run: |
          echo $TZ
          #!/bin/bash
          # 実行時刻を取得 (UTC)
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # スケジュールされた時刻 (この例では毎時0分なので、現在の時刻から分と秒を0に設定)
          scheduled_time=$(date -u +"%Y-%m-%dT%H:30:00Z")

          # 差分を計算 (秒)
          diff=$(($(date -u -d "$current_time" +"%s") - $(date -u -d "$scheduled_time" +"%s")))
          echo $diff

          # JSONファイルが存在しなければ作成する
          if [ ! -f schedule-diff.json ]; then
            echo "[]" > schedule-diff.json
          fi

          # JSONに結果を追記
          jq --arg current_time "$current_time" --arg scheduled_time "$scheduled_time" --argjson diff $diff '. += [{"current_time": $current_time, "scheduled_time": $scheduled_time, "difference": $diff}]' schedule-diff.json > temp.json && mv temp.json schedule-diff.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add schedule-diff.json
          git commit -m "Update schedule-diff.json"
          git push
