name: secret mask test
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/secret-mask-test.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_VAR: ${{ secrets.SECRET_VAR }}
      VAR: ${{ variables.SECRET_VAR }}
    steps:
      - name: echo secrets.SECRET_VAR
        run: echo ${{ secrets.SECRET_VAR }}
      - name: echo via env
        run: echo ${{ env.SECRET_VAR }}
      - name: echo variables
        run: echo ${{ variables.VAR }}
      - name: echo via env
        run: echo ${{ env.VAR }}
