run-name: subshell test

on: [push, pull_request]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hoge fuga" | read -r var1 var2
          echo $var1
          echo $var2
