name: subshell test

on: [push, pull_request]

jobs:
  pipe:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hoge fuga" | read -r var1 var2
          echo $var1
          echo $var2
  herestring:
    runs-on: ubuntu-latest
    steps:
      - run: |
          read -r var1 var2 <<< "echo hoge fuga"
          echo $var1
          echo $var2
  tmp_output:
    runs-on: ubuntu-latest
    steps:
      - run: |
          tmp.txt=$(echo "hoge fuga")
          read -r var1 var2 < tmp.txt
          echo $var1
          echo $var2
